#!/usr/bin/env python
# Copyright (c) 2014 Alexandre Quessy
# See LICENSE for details.
"""
Receives Art-Net messages using txartnet
"""
if __name__ == "__main__":
    raise NotImplementedError("To do")

